### ISSUE TITLE
TypeError from trying to convert NoneType to int in sportsreference.ncaaf.teams.schedule.dataframe_extended

### ISSUE THREAD

**Issue by ChrisHeneghan** [roclark/sportsreference#3] opened 2018-08-27 20:37 UTC
``Traceback (most recent call last):

``  File "./scrape.py", line 28, in <module>

``    sched = getScheduleDF(team, yr)

``  File "./scrape.py", line 15, in getScheduleDF

``    df = sched.dataframe_extended

``  File "/home/chris/.local/lib/python3.6/site-packages/sportsreference/ncaaf/schedule.py", line 459, in dataframe_extended

 ``   frames.append(game.dataframe_extended)

``  File "/home/chris/.local/lib/python3.6/site-packages/sportsreference/ncaaf/schedule.py", line 159, in dataframe_extended
``    return self.boxscore.dataframe
``  File "/home/chris/.local/lib/python3.6/site-packages/sportsreference/ncaaf/boxscore.py", line 240, in dataframe
``    'away_first_downs': self.away_first_downs,
``  File "/home/chris/.local/lib/python3.6/site-packages/sportsreference/ncaaf/boxscore.py", line 374, in away_first_downs
``    return int(self._away_first_downs)
``TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'``

**Comment by roclark** [comment] 2018-08-28 01:37
@ChrisHeneghan thank you for notifying me of this issue! Looks like you are using the pip package (v0.1.0 since that is the only released version), is that correct? Also, I see you have a `yr` variable in your `getScheduleDF()` call. Which year are you making the query for? If it is for the upcoming season starting this week (2018), then I believe the issue derives from the fact that not every team has played a game yet and `sportsreference.com` doesn't create blank or default stats for those teams, so the code is trying to parse something that doesn't exist. I will work on an update for this and skip over teams that don't have any stats yet.

If you are seeing this for another year, then the issue is something different and we will need to keep digging at the root cause.

Thanks again for pointing this out! I appreciate it!

**Comment by ChrisHeneghan** [comment] 2018-08-28 03:01
Yes, I was using the pip package.
I don't know exactly what year it was, but it was from between 2000 and 2017, so not 2018.
Just from using this package a little bit this afternoon, I've noticed that there are occasional issues where missing data or incorrectly formatted data from Sports-Reference causes issues like this. (For example I ran into some incorrectly formatted dates)

Thank you soooo much by the way for working on the project. It looks promising to be immensely useful to aspiring data scientists/handicappers like me.

**Comment by roclark** [comment] 2018-08-28 17:29
@ChrisHeneghan Good to know! I'm able to duplicate this on my end - as you saw, it looks like there are some empty boxscores for past seasons (take the [2001 Orange Bowl](https://www.sports-reference.com/cfb/boxscores/2001-01-03-florida-state.html) for example). One of the updates I was planning on including with my 0.2.0 release was better error handling for missing/incomplete data, but I still have more features that I would like to include prior to the next feature release. Instead, I will go ahead and create a patch for this now and release a new version which includes this fix before my 0.2.0 release so that we can get you back up and running quicker.

I really appreciate the kind thoughts! I have a lot of plans for this project going forward, and it always helps to see others share in that excitement! All of this feedback is helpful to making this tool as useful as can be for everyone!

**Comment by ChrisHeneghan** [comment] 2018-08-29 06:30
@roclark I've been finding this project very useful, and I would like to contribute if possible.

Would you mind informing me what your vision is for the 0.2.0 release? Specifically with the error handling. I think the easiest fix would be to just handle those exceptions by inserting a default value like the minimum integer or something. Then you could add a data member to the class that is a dictionary with the values that caused errors as values and their respective fields as keys. The biggest thing to work towards is robustness so that if I'm pulling all the stats from the last ten years for example, I don't have to worry about one bad page from the website stopping the whole script. 

Also, I think it would be really useful if there was a way to get the uri string from a Boxscore object, because if I'm pulling a whole season's data, I'm gonna get the boxscores from a Schedule object instead of uri strings. However, I would find it useful to be able to easily include the uri string in my table.

Thanks again for working on this, I would love to contribute.

**Comment by roclark** [comment] 2018-08-29 21:18
@ChrisHeneghan I'm definitely open to people contributing! That's the whole reason I went open-source with this project. 😄

I think I will start doing more things "in the open" now that I have a release in the wild and am getting some issues filed. I will probably create a separate issue/milestone for my release plans for 0.2.0, but it basically boils down to the following major items:

- Add error handing for properties (more on that below)
- Create a Roster/Player class for all sports (see #2 for an example of what I mean by this)
- Add NCAAB/NCAAF rankings and conference information (already complete for NCAAB, just need to work on NCAAF)

I am also in the process of setting up a personal Jenkins server to continually build/deploy the latest code.

I definitely agree with you on adding robustness to the properties as, like you, my goal is to be able to loop over a large amount of data and I would hate for all of that to come crashing down thanks to one misnamed tag on a single page. I've already started working on an update to enable this, but I basically am planning on creating new property decorators for all common properties and include error handing in the decorators. I was originally planning on using a default value of `0` (or `0.0` for floats) for the error handling, but after much debate, I decided to use a value of `None` for any values that can't be parsed. My reasoning is that there is a statistical difference between `None` and `0` when it comes to data analysis. With `None`, the end-user has the freedom to choose how he/she wants to handle data that is not present. For example, say the number of passing touchdowns is not recorded for a football game. If a trained machine learning algorithm determines that teams who score a lot of passing touchdowns in a game tend to win most games, it might come across a data point where the passing touchdowns is filled with the default value of `0` when it actually wasn't recorded, and wrongly predict that a team won't win due to the recordkeeping error. With the value set to `None`, the user can decide on special handling, such as dropping all rows with `None`, using a mean/median value, or another method. With a default value of any other number, it is challenging to determine whether that value was filled by default or if the team actually got `0` for that category (ie. a team got shutout and therefore scored zero passing touchdowns). Do you agree with these assumptions of mine? Or do you have another suggestion as to how I should handle defaults?

Also, I agree with you on finding a better way to get the uri string. I haven't put much thought into this one yet, but I'm open to suggestions. Perhaps this could be tracked in another issue?

I've been working on the implementation of the above error handling in the `decorate-properties` branch which you are welcome to follow along with if desired.

Lastly, I will spend some time on community engagement pieces and add more information on contributing, issues, etc. Again, I'm very open to contributions to make this project successful!

**Comment by roclark** [comment] 2018-09-03 21:06
@ChrisHeneghan I finished my error parsing update and created PR #4. I ran through a long test of historical seasons for all sports and everything appears to be working as expected. Let me know if you have any thoughts on that update - if not, I will go ahead and merge the PR and close this issue.

**Comment by roclark** [comment] 2018-09-04 13:15
@ChrisHeneghan just FYI, I created [v0.1.1](https://github.com/roclark/sportsreference/releases/tag/v0.1.1) which is similar to #4 in that it fixes all of the issues I encountered with v0.1.0. The release is now up on PyPI and can be upgraded/re-installed to make use of the fixes. I will still keep #4 open for now in case you have any feedback.

**Closed** 2018-09-06 21:15 UTC
Labels: bug
