### ISSUE TITLE
Bug in data column - ncaaf boxscore

### ISSUE THREAD

**Issue by kbrahm** [roclark/sportsreference#47] opened 2018-12-28 03:36 UTC
**Describe the bug**
Everything looks good, except the column under stadium is empty, and the column for time has the stadium name and location in the row.

**To Reproduce**
Sample code which causes an issue.
```python
from sportsreference.ncaaf.boxscore import Boxscore
import csv

game_data = Boxscore('2018-01-08-georgia')
print(game_data.home_points)  # Prints 23
print(game_data.away_points)  # Prints 26
df = game_data.dataframe  # Returns a Pandas DataFrame of game metrics
print (df)

df.to_csv('box.csv')
```

**Expected behavior**
Stadium name to be in stadium column and time to be in time column

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsreference Version [e.g. 0.2.0 or commit hash if using code]

**Additional context**
N/A

**Comment by roclark** [comment] 2018-12-29 03:40
Hello again @kbrahm, thanks for opening up this new issue. I’ve had lots of issues parsing the game meta information for all sports. I can confirm that I’m seeing what you see on my end as well. I will try and dig deeper tomorrow to see if the bowl games interfere with the parsing scheme, or if this also appears in other sports. I will let you know what I find and create a fix for this and include it with a patch release of 0.3.2.

**Comment by roclark** [comment] 2018-12-29 16:10
I created PR #49 which updates the parsing scheme to properly pull boxscore information from sports-reference.com. I originally used a scheme that had an expected layout of information on the page, but whenever that changes, the incorrect information would be populated in the class properties. This problem just became visible since it appears sports-reference.com removed the game time from the boxscore page, which threw off the scheme. The new scheme is much more flexible, but unfortunately it looks like the time will no longer be applied for some games since it was removed from the site.

**Closed** 2018-12-29 16:52 UTC
Labels: bug
